### ISSUE TITLE
GF_Arabic_Core glyphset FAILS

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Oi#13]
@davelab6 I am not sure I understand these two FAILS for the Arabic set. 

What is this attachment to None?
And what is the Alef Maksura buffer fail?

* 🔥 **FAIL** <p>GF_Arabic_Core glyphset:</p>
<table>
<thead>
<tr>
<th align="left">Language</th>
<th align="left">FAIL messages</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">ar_Arab (Arabic)</td>
<td align="left">Shaper didn't attach uni0655 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni064D to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0650 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0670 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0653 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0654 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni064B to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni064C to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni064E to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni064F to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0651 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0652 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">.medi version of ARABIC LETTER ALEF MAKSURA; both buffers returned space=1+0</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">.init version of ARABIC LETTER ALEF MAKSURA; both buffers returned space=0+0</td>
</tr>
</tbody>
</table>
 [code: failed-language-shaping]

* 🔥 **FAIL** <p>GF_Arabic_Core glyphset:</p>
<table>
<thead>
<tr>
<th align="left">Language</th>
<th align="left">FAIL messages</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">fa_Arab (Persian)</td>
<td align="left">Shaper didn't attach uni064D to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni064B to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni064C to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0651 to None</td>
</tr>
<tr>
<td align="left">^</td>
<td align="left">Shaper didn't attach uni0654 to None</td>
</tr>
</tbody>
</table>
 [code: failed-language-shaping]

**Comment by kosbarts** [comment]
@yanone did you encounter these FAILS this time? If not then we can close this issue.

**Comment by yanone** [comment]
Yes. The current fontbakery has a better output which shows the actual letters. One base glyph I fixed in the PR (wawhamza), the remaining ones I checked manually for correct mark positioning with a positive result, so I must conclude that the shaping check is incorrect here. I would close it, and I will also instruct our reviewers to ignore these.

**Comment by yanone** [comment]
The alefmaksura FAIL is also meaningless, because the letter is only used in final and isolated form. Again this is a problem in the check.
