### ISSUE TITLE
Fontbakery issue on production Action

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Oi#6]
Hi @RosaWagner 

I just pushed the latest version of Oi, which has been updated with Cyrillic and Tamil support. The Action is running fine but there seems to be some issue with fontmake report:
https://github.com/kosbarts/Oi/runs/4093178154?check_suite_focus=true

Can you have a look at it?

K.

**Comment by RosaWagner** [comment]
Ah we are having this error everywhere at the moment, it has been introduced with the latest version of fontbakery
https://github.com/googlefonts/fontbakery/issues/3495

**Comment by RosaWagner** [comment]
If you put the previous version of fontbakery in the requirements, it may work again. Otherwise a PR will fix that issue soon. If you are ready with the font, please update us there: https://github.com/google/fonts/issues/3820 :)

**Comment by kosbarts** [comment]
@RosaWagner it is ready. As far as I saw in the fontbakery report it shouldn't have any problems.
