### ISSUE TITLE
phook suggestion

### ISSUE THREAD

**Issue by EbenSorkin** [kosbarts/Oi#8]
Denis recently noted that the better default shape for the biggest users of this letter is one where the hook doesn't emerge from the stem but comes from the bowl instead. I have mocked up what this might be like on the far right with the chook as a reference. This is just for the lowercase letter.

<img width="878" alt="image" src="https://github.com/kosbarts/Oi/assets/2181213/9c349790-11b4-4fae-b51b-3d6438db74aa">

**Comment by kosbarts** [comment]
I've updated it. Thanks.
